version: 2

release:
  draft: true
  replace_existing_draft: true
  footer: |
    ## Contributors
    Thanks to all the [contributors](https://github.com/dragonflyoss/dragonfly/graphs/contributors)! ❤️

before:
  hooks:
    - hack/update-version-gorelease.sh
    - make build-manager-console
    - go mod download

builds:
  - main: ./cmd/scheduler
    id: scheduler
    binary: scheduler
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X d7y.io/dragonfly/v2/version.Major={{ .Major }}
      - -X d7y.io/dragonfly/v2/version.Minor={{ .Minor }}
      - -X d7y.io/dragonfly/v2/version.GitVersion={{ .Tag }}
      - -X d7y.io/dragonfly/v2/version.GitCommit={{ .ShortCommit }}
      - -X d7y.io/dragonfly/v2/version.BuildTime={{ .Date }}
      - -X "d7y.io/dragonfly/v2/version.Gotags=none"
      - -X "d7y.io/dragonfly/v2/version.Gogcflags=none"
    env:
    - CGO_ENABLED=0

  - main: ./cmd/manager
    id: manager
    binary: manager
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X d7y.io/dragonfly/v2/version.Major={{ .Major }}
      - -X d7y.io/dragonfly/v2/version.Minor={{ .Minor }}
      - -X d7y.io/dragonfly/v2/version.GitVersion={{ .Tag }}
      - -X d7y.io/dragonfly/v2/version.GitCommit={{ .ShortCommit }}
      - -X d7y.io/dragonfly/v2/version.BuildTime={{ .Date }}
      - -X "d7y.io/dragonfly/v2/version.Gotags=none"
      - -X "d7y.io/dragonfly/v2/version.Gogcflags=none"
    env:
    - CGO_ENABLED=0

archives:
  - name_template: "dragonfly-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats: ["tar.gz"]
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: Dependency updates
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug Fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Chores"
      order: 9999
